language: node_js

node_js: "8"

os: linux

addons:
  sonarcloud:
    organization: "vkgeo-github"
    token:
      secure: "LFgQm+3l+qcZv0OVs2Ud6ShZIAUOFPXXhCKRuRRxkT26BCRxfFkZjthuxBWEUIme5NwBQcaD69RTK7jMTjXjlKL2MlkLlCof5wybm8hBGFGebuaqpu3RpVZ6fEr/cUfsPhHLJYO5QW+OfCGoOOj0cVFqS5Hmi1CRy/6taIoqKjmz5BBjf5JXSRAnG2ijKjRL3T2Nk2TseT8tw6fxlgaMAfQCpy7ULlWoENU2/Cs97uV2rcgP75GkmcpDRhvg374ywz1Yxm5nIvXVmpmmiaGRE7UnEA/htLXo7jTfZYERKOzthtnhMdhhZH8nKSiyb0kPZUgrgKHJsKbAKbuMdDUaM6uCxC9Gg3aZNikAQCLOQXn4uzlgpyzRWIK3hu4Z9F71cJELUUf1MKh9NCxKLDx/KodY4ykN+8MrCJ5WI5zPPmmbgc5trcgdt/IhiswfoAt1TQyoUdJCWojWX7IXfXw2j7D4D6/D2NnWU2LMFo+kFpA3HJw3Zvv8/2Bf4dSiOwhN8RoSotZ88c+yO1wrRlku8Y/W6d740GW/fQfaId4hvud1EzfjreHzt2LrsbMdX5Dujplva7OmbDvsy4F0ylVI7UpPNlOKWbgwn2P8u88KMYNMf3v5NdTpSZt4kfifE9bX4Pt4/iQ0bXsHcDmWvsv7EK2bOXd5kO2aLL2KIeQsRRQ="

script:
  - |
    echo && \
    echo "--------- UNSHALLOW GIT FOR SONAR ---------" && \
    echo && \
    git fetch --unshallow && \
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then \
        echo && \
        echo "-------------- SONAR SCANNER --------------" && \
        echo && \
        sonar-scanner -Dsonar.projectKey=vkgeo_vkgeo-web \
                      -Dsonar.projectName="VKGeo Web" \
                      -Dsonar.sources=. \
                      -Dsonar.sourceEncoding=UTF-8 \
                      -Dsonar.exclusions=vk_iframe_app/lib/**/*; \
    fi
