language: node_js

node_js: "8"

os: linux

env:
  global:
    - secure: "co2KCujsbEUoQ3EOY888nkX8nfjcaRJU/pD+kTt7ObortBzzvzBALbUXM91ZGUo3TNlBf/Q4KSKsPZflzNx8dDDkeMlwVmdsixyG1eWHdX32k8hUdSw6VRXMJq5x73XVhc83CwSyK2NJS3P96knJgYj82E02qOPCJNtKKgmRXChTyhN0v5amQaAEpmoRz41E+105gRrrozOHDdho6RQj+qeVJiTonG4rAt2ux+ITKDjEfxS4GewQQtMPkjMbygpYlBYB2Y17kcyxMUEQa3AxBTh/02wiYvQEh/Q3L2qreD/Q24WVPLnVqrNepPzDVQdUGXUyeSwczMhX7pbpXyMGY8QLtioFKz9ENJU0NT4m187149G+MMR6umX/DEXC1bOKZx31W7Zj8i8t8mS76xA3zxkQerMFHY+WtkfMkOWzdlv2XxfGgNnZqfqv82CRfatMbSnekmJVpDyzYp7EEJozhJCSoA0SeH3mkFcZpX5/8hKUJ+xKBAV12sak2QTGSAe79c497NVpD176z8xnMZY4BTHG75rqAWzxhJDrk4xPmNqW/Q5nVBqECu8qycWePrNFXuRu3SVVkyzk8A2onFYQ0JG1l1dPabjSqAy0uoT2uWE8ZbIkoBXIgO297ay/jnEwwrWJfOrK4WcMwb78qYBmfFi8F0I72uGMdQvvZ7PY9HI="

addons:
  coverity_scan:
    project:
      name: "vkgeo/vkgeo-web"
      description: "VKGeo Friends on Map for VKontakte Web app"
    notification_email: oleg.derevenetz@gmail.com
    build_command_prepend: ""
    build_command: "--no-command --fs-capture-search vk_iframe_app/"
    branch_pattern: coverity_scan

before_script:
  - |
    echo
    echo "------- UNSHALLOW GIT FOR COVERITY --------"
    echo
    git fetch --unshallow

script:
  - |
    if [[ -f cov-int/scm_log.txt ]]; then
        echo
        echo "---------- BEGIN OF SCM_LOG.TXT -----------"
        echo
        cat cov-int/scm_log.txt
        echo
        echo "----------- END OF SCM_LOG.TXT ------------"
        echo
    fi        

    exit 0
